- name: Install Apache
  become: true
  become_user: root
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: Install Git
  become: true
  become_user: root
  ansible.builtin.yum:
    name: "git"
    state: present

- name: Install EPEL release
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y

- name: Install dnf-utils and Remi repository
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: dnf install dnf-utils http://rpms.remirepo.net/enterprise/remi-release-9.rpm -y

- name: Reset PHP module
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: dnf module reset php -y

- name: Enable PHP 7.4 module
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: dnf module enable php:remi-7.4 -y

- name: Install PHP and extensions
  become: true
  become_user: root
  ansible.builtin.yum:
    name:
      - php
      - php-opcache
      - php-gd
      - php-curl
      - php-mysqlnd
    state: present

- name: Install MySQL client
  become: true
  become_user: root
  ansible.builtin.yum:
    name: "mysql"
    state: present

- name: Start PHP-FPM service
  become: true
  become_user: root
  ansible.builtin.service:
    name: php-fpm
    state: started

- name: Enable PHP-FPM service
  become: true
  become_user: root
  ansible.builtin.service:
    name: php-fpm
    enabled: true

- name: Set SELinux boolean for httpd_execmem
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: setsebool -P httpd_execmem 1

- name: Clone a repo
  become: true
  become_user: root
  ansible.builtin.git:
    repo: https://github.com/citadelict/tooling.git
    dest: /var/www/html
    force: yes

- name: Copy HTML content to one level up
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: cp -r /var/www/html/html/ /var/www/

- name: Start httpd service, if not started
  become: true
  become_user: root
  ansible.builtin.service:
    name: httpd
    state: started

- name: Recursively remove /var/www/html/html directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent
